version: "3.7"

services:
  aspnet:
    build: 
      context: ./aspnet
    ports:
      - 3001:80
  next-app:
    build:
      context: ./next-app
      target: deps
    volumes:
      - ./next-app:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev