version: '3.7'

volumes:
  wp_html:
  mysql_db:

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_html:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_db:/var/lib/mysql